### ISSUE TITLE
Modal in Bilinguals 

### ISSUE THREAD

**Issue by stephan-schmidt** [ccmdesign/100-questions-components#4]
Ref: http://dev.the100questions.org/bilinguals.html

Next step is to get the modal window to be open in Bilinguals. I transferred the DOM from the modal.html for the layovers to the bilingual.html, at least the one I think is necessary, the script is also pulled, yet the window will not open when clicking on the Button. What do I need to transfer as well? DO I miss something here?

**Comment by arthurbergmz** [comment]
Hey, Stephan! How is it going?

I'm sorry, but I didn't get your question... I just accessed the page you mentioned and the modal window is opening.

I have two suggestions: you will have to create a modal for each Bilingual or watch for the Bilingual the user clicks on (preferred option, since you're using Vue - something like @click="setCurrentBilingual(bilingual.bio)").

**Comment by stephan-schmidt** [comment]
Yes, I figured the modal opening with vue now. Works great for me and I read in the loop the bilingual.id which triggers a vue function that parses for this id and the content of it. I'll let you know the result.

**Comment by stephan-schmidt** [comment]
Arthur,  I set could use the modal now and pull in the data as well. http://dev.the100questions.org/bilinguals.html 

As I had to rework the HTML because using the VUE modal, the structure changed and also the DOM. I understand that the CSS you provided is set up on a certain DOM structure. Now I have a difficulty to understand the CSS to apply to the modal in particular the Closing Button, the turquoise bar at the top of the modal as displayed here. https://xd.adobe.com/view/1f3640db-6c33-44e8-46a8-28c1f4ff1b6f-6907/screen/fbdf42b0-2072-46ff-9d4d-2a766f04bc6c/BIlingual-modal

I probably can fiddle in the edges too but can your hint me or provide a tweak to the CSS you provided so both elements described above appear? Thanks so much.

**Comment by arthurbergmz** [comment]
Hey, Stephan! How is it going?

So, the close button on the modals depends on the parent element having the classes "modal-window open". But since you're using your own code, I just took a look, added the element `<button class="modal-window__close" aria-label="Close"><img src="/images/close.svg" /></button>` between `modal-container::before` and `<div data-modal-id="portrait-modal" class="modal">`, and added `opacity: 1` and `transform: none` to the "modal-window__close" class. With that, I got the close button on your modal.

**Comment by stephan-schmidt** [comment]
Thanks, did that and the close button appears, it just jumps in the right upper corner after fully loaded. See picture. Also the turquoise bar jumps when loaded. I tweaked a bit the CSS before and took out  top:0 for example. Any other workaround there or at first, are you able to replicate it? 
![image](https://user-images.githubusercontent.com/1506096/62234170-1fb70600-b398-11e9-9c17-38af19b54b9a.png)

**Comment by arthurbergmz** [comment]
@stephan-schmidt Add `position: relative` to `.modal-container`.

Cheers,
Arthur.

**Comment by stephan-schmidt** [comment]
> @stephan-schmidt Add `position: relative` to `.modal-container`.
> 
> Cheers,
> Arthur.

works!
